# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Love Comes Down
email: natasha.beljin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Love Comes Down is a children's book written by Natasha Frasch and illustrated by Avery Mefford. Site design by Preston Frasch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lovecomesdown.org" # the base hostname & protocol for your site
twitter_username: tashafrasch
github_username:  preston-frasch

# Build settings
markdown: kramdown
